### ISSUE TITLE
Ability to use space instead of ctrl-space

### ISSUE THREAD

**Issue by gderosa** [sblask/webextension-image-forward#6]
I know this was somewhat discussed in #1, but you sent a link to an add-on that, a few years later, no longer exists. I tried a number of add-ons for shortcut management but none addressed the issue. Thanks!

**Comment by sblask** [comment]
I changed the shortcut for exiting iteration mode since to avoid the conflict. If you want to change the shortcuts, you'll have to use Chrome, because despite the mission statement, the switch to webextension did not add better shortcut handling (yet?) while taking away the existing possibilities.

Now to the title of this issue, using only space will not be possible, even in Chrome, unless I implement a lot of logic to handle this. But I won't because there are so many scenarios where this can interfere with websites and other extensions. While a broken extension would be the least of the problems, websites where space doesn't work any more would be a huge and it would be very hard for a user to figure out where the problems come from.
